kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    name: webapp
  ports:
    - protocol: TCP
      nodePort: 30100
      port: 4000
      targetPort: 8080
  type: LoadBalancer
